### ISSUE TITLE
Request for Ayu theme port

### ISSUE THREAD

**Issue by nigurr** [joonro/ConEmu-Color-Themes#21]
https://github.com/dempfi/ayu
https://github.com/ayu-theme/ayu-colors

Can we please port these colors to ConEmu theme :)

**Comment by Van-Dame** [comment]
Yes please!

**Comment by joonro** [comment]
This does look pretty .. thanks for letting me know.

**Comment by joonro** [comment]
Added.

**Comment by yelfathi** [comment]
Hi by looking at the hex values the Ayu Dark theme does not correspond to the ayu color palette. Can you please fix it, thanks?

P.S: How do you generate the conemu themes?
