### ISSUE TITLE
Extended foreground colors are no longer supported

### ISSUE THREAD

**Issue by dguo** [joonro/ConEmu-Color-Themes#23]
Hi, just in case you weren't aware already, ConEmu removed the extended foreground colors feature in [build 180318](https://conemu.github.io/blog/2018/03/18/Build-180318.html), which was [released](https://github.com/Maximus5/ConEmu/releases/tag/v18.03.18) on 2018-03-18. See Maximus5/ConEmu#1595.

It may be worth it to make a note of that in the README and to update the scripts and themes in this repo.

**Comment by joonro** [comment]
Thanks for letting me know and I'm sorry for the late reply. I will take a look.

**Comment by joonro** [comment]
Resolved by 67c83223b4802d068de15860efd270c8494509f0.
