### ISSUE TITLE
railscasts theme?

### ISSUE THREAD

**Issue by blacksmoke26** [joonro/ConEmu-Color-Themes#5]
Can you create "base16-railscasts" theme for ConEmu? Would be great if you can.

Source: [https://chriskempson.github.io/base16/](https://chriskempson.github.io/base16/)

![image](https://cloud.githubusercontent.com/assets/425744/20458871/ae5d3f78-aed2-11e6-96b4-2b1d2c48f31d.png)

**Comment by joonro** [comment]
Hi - sorry for the late reply. I just added both light and dark themes for this. Usually base16 themes do not have enough colors to populate all the colors, so I had to reuse a couple of colors more than once. Hope you like it.

**Comment by blacksmoke26** [comment]
thanks for your hard work! Love it! 👍
