### ISSUE TITLE
Can't get themes to load

### ISSUE THREAD

**Issue by ckam03** [joonro/ConEmu-Color-Themes#7]
I ran the script and it seems like it worked but I don't see the theme in colors??

**Comment by shiitake** [comment]
Can you see the new theme(s) listed in the ConEmu settings?

Can you paste the theme you added as well the part of conemu.xml with the color data?

**Comment by ckam03** [comment]
That's what I meant. Settings, colors, schemes. The theme isn't there but it's the moe-dark theme.  
[moe-dark.txt](https://github.com/joonro/ConEmu-Color-Themes/files/767909/moe-dark.txt)

**Comment by shiitake** [comment]
The moe-dark.txt that you provided is missing the closing </key> at the end. That would probably cause the theme to not load correctly. 

You might try removing it, updating the moe-dark.txt and then try adding it again. Or you can manually edit the conemu.xml config and add the </key> manually.

**Comment by ckam03** [comment]
Oh no, it's there. Looks like I just screwed it up when copying the code into the other file.

**Comment by shiitake** [comment]
can you upload your conemu.xml file?

**Comment by ckam03** [comment]
[ConEmu.txt](https://github.com/joonro/ConEmu-Color-Themes/files/768144/ConEmu.txt)

**Comment by joonro** [comment]
I just downloaded your `ConEmu.xml`, change its encoding to `UTF-8` (it was in `UTF-16 with BOM`, and it gave me an error when I try to load it with `ConEmu`), and it seems to work - I do see moe-dark and Monokai in theme list:

![image](https://cloud.githubusercontent.com/assets/1063143/22864669/6bdf9656-f11b-11e6-9055-0ac07f070985.png)

**Comment by nitin88** [comment]
Hi,

Even I am facing the same issue. I can't see any one of these themes. They are present in ConEmu.xml, but not visible in palettes/settings

![image](https://cloud.githubusercontent.com/assets/4945664/22988049/dabcf024-f3d6-11e6-9fd1-59ce44389131.png)
[ConEmu.txt](https://github.com/joonro/ConEmu-Color-Themes/files/777956/ConEmu.txt)

Running ConEmu 170118 (latest version)

**Comment by shiitake** [comment]
hi @nitin88 it looks like at **line 685** you don't have the correct count. 
    <value name="Count" type="long" data="0"/>

The data attribute value should be 12

**Comment by nitin88** [comment]
Thanks. that fixed the issue

**Comment by shiitake** [comment]
@ckam03 were you able to resolve this one?

**Comment by ckam03** [comment]
Yes, I was. Thanks!
